import enums.IniEntryType

fun main() {
    val plainCapitalizedBooleanEntry = IniEntry("PlainCapitalizedBoolean", IniValue(true), IniEntryType.Plain)
    println("PlainCapitalizedBooleanEntry:")
    println(plainCapitalizedBooleanEntry)
    val plainBooleanEntry = IniEntry("PlainBoolean", IniValue(true, false), IniEntryType.Plain)
    println("PlainBooleanEntry:")
    println(plainBooleanEntry)
    val plainStringEntry = IniEntry("PlainString", IniValue("Hello World"), IniEntryType.Plain)
    println("PlainStringEntry:")
    println(plainStringEntry)
    val plainIntegerEntry = IniEntry("PlainInteger", IniValue(42), IniEntryType.Plain)
    println("PlainIntegerEntry:")
    println(plainIntegerEntry)
    val plainFloatEntry = IniEntry("PlainFloat", IniValue(3.14f), IniEntryType.Plain)
    println("PlainFloatEntry:")
    println(plainFloatEntry)
    val plainStructEntry = IniEntry("PlainStruct", IniValue(mapOf("key" to IniValue("value"), "key2" to IniValue(24))), IniEntryType.Plain)
    println("PlainStructEntry:")
    println(plainStructEntry)
    val commaSeparatedArrayEntry = IniEntry("CommaSeparatedArray", listOf(IniValue(true), IniValue(false)), IniEntryType.CommaSeparatedArray)
    println("CommaSeparatedArrayEntry:")
    println(commaSeparatedArrayEntry)
    val repeatedLineArrayEntry = IniEntry("RepeatedLineArray", listOf(IniValue("Hello"), IniValue("World")), IniEntryType.RepeatedLineArray)
    println("RepeatedLineArrayEntry:")
    println(repeatedLineArrayEntry)
    val indexedArrayEntry = IniEntry("IndexedArray", listOf(IniValue(1), null, IniValue(2)), IniEntryType.IndexedArray)
    println("IndexedArrayEntry:")
    println(indexedArrayEntry)
    val mapEntry = IniEntry("Map", mapOf("key1" to IniValue(1), "key2" to IniValue(2)), IniEntryType.Map)
    println("MapEntry:")
    println(mapEntry)
}